name: eco_chat_bot
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  font_awesome_flutter: ^10.6.0
  fluttertoast: ^8.2.12
  firebase_core: ^2.24.2
  google_sign_in: ^6.1.6
  firebase_auth: ^4.16.0
  flutter_bloc: ^9.1.0
  smooth_page_indicator: ^1.1.0
  hive_flutter: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  equatable: ^2.0.5
  meta: ^1.9.1
  rxdart: ^0.28.0
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  wave: ^0.2.2
  dotted_border: ^2.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.2.1
  logging: ^1.3.0
  file_picker: ^10.1.2
  mime: ^1.0.0
  url_launcher: ^6.1.7
  intl: ^0.20.2
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  timeago: ^3.7.1
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 # flutter pub run flutter_launcher_icons

flutter_launcher_icons:
  image_path: "assets/logo/eco_chat_bot-logo.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - .env
    - assets/logo/
    - assets/icons/
    - assets/icons/nav_bar/
    - assets/images/
    - assets/images/avatar/
    - assets/images/ai_models/
    - assets/logo/eco_chat_bot-logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: Mercadillo
      fonts:
        - asset: fonts/mercadillo/Mercadillo-Bold.ttf
          weight: 700
