name: "Build & Release"

on:
  pull_request:
    branches:
      - feature/chat-ai
  push:
    branches:
      - feature/chat-ai

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest # Changed to macOS runner for iOS build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Android)
        run: flutter build apk --release --split-per-abi

      - name: Build iOS app (no code-signing)
        run: flutter build ios --release --no-codesign # Build iOS app without code-signing

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/Runner.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
